### ISSUE TITLE
all_ans.json fil

### ISSUE THREAD

**Issue by hc0527** [sergiotasconmorales/imp_vqa#1]
Hello dear author, how do I get the all_ans.json file you mentioned in the create_answers_dict.py file?

**Comment by sergiotasconmorales** [comment]
@hc0527 Sorry, I forgot to include that file. I updated the README with the link ("LXMERT answers") to the file, which comes from the original LXMERT repo. I'm still testing all the steps in the repo, so sorry in advance for any errors. By the end of this week the repo should be completely functional.

**Comment by hc0527** [comment]
> @hc0527 Sorry, I forgot to include that file. I updated the README with the link ("LXMERT answers") to the file, which comes from the original LXMERT repo. I'm still testing all the steps in the repo, so sorry in advance for any errors. By the end of this week the repo should be completely functional.

Thank you for your timely reply, and good luck with your work!
