### ISSUE TITLE
File not found.

### ISSUE THREAD

**Issue by LemonQC** [sergiotasconmorales/imp_vqa#2]
[Errno 2] No such file or directory: './data/vqaintrospect/VQAIntrospect_train_no_duplicates_withidrelv1.0.json'

**Comment by sergiotasconmorales** [comment]
@LemonQC Can you provide more information about which script produced the error? Are you trying to generate the annotations about relations for Introspect?

**Comment by LemonQC** [comment]
When I run  "python introspect/curate_introspect.py", I found no such file.

**Comment by sergiotasconmorales** [comment]
@LemonQC That file should be generated by the script `remove_duplicates.py`. Were you able to run that one successfully?

**Comment by LemonQC** [comment]
> @LemonQC That file should be generated by the script `remove_duplicates.py`. Were you able to run that one successfully?

Yes， I re-run the whole process and succeed. Many Thanks.
