### ISSUE TITLE
Errors when preparing datasets.

### ISSUE THREAD

**Issue by LemonQC** [sergiotasconmorales/imp_vqa#4]
![image](https://github.com/sergiotasconmorales/imp_vqa/assets/30914380/c92ca39c-c6b6-4568-a13f-51009948bb00)
When I download the data from the website. And then I run the training code. I found some files are missing. That's to say, I must run the data preparation code.

**Comment by sergiotasconmorales** [comment]
@LemonQC Thanks. I'll have a look and upload any missing files this week

**Comment by LemonQC** [comment]
Hi，thanks for your help first. I hope you can share me with the training process about dme. I found the features and scripts are hard to modify.






Best wishes.


| |
Shandong University
|
|
***@***.***
|
---- Replied Message ----
| From | Sergio Tascon ***@***.***> |
| Date | 5/30/2023 16:37 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [sergiotasconmorales/imp_vqa] Errors when preparing datasets. (Issue #4) |

@LemonQC Thanks. I'll have a look and upload any missing files this week

**Comment by sergiotasconmorales** [comment]
@LemonQC I tried to train with the downloaded data and it worked fine. Can you share the error you get about missing files?

About DME, I'll try to add it to the repo in the following days/weeks.

**Comment by LemonQC** [comment]
Wow, I am so sorry. I re-download the data and it works.
