### ISSUE TITLE
can't download the final version of datasets

### ISSUE THREAD

**Issue by Wiikk** [sergiotasconmorales/imp_vqa#5]
Hi, I can't download the given final version of the datasets from https://zenodo.org/record/7777878.
Could you please check the link? Thank you.

**Comment by sergiotasconmorales** [comment]
@Wiikk The link is working fine for me. At the end of the website you can see the Download button. Note that it only contains questions and answers, not the images. The images must be downloaded separately, as described in the README.

**Comment by Wiikk** [comment]
@sergiotasconmorales Thanks for answering. I have got these datasets.
